export const GET_LIST_MOVIES = "GET_LIST_MOVIES";
export const GET_DETAILS_MOVIE = "GET_DETAILS_MOVIE";
export const GET_LINK_MOVIE = "GET_LINK_MOVIE";
export const GET_LIST_BRANCHES = "GET_LIST_BRANCHES";
export const GET_LIST_THEATERS = "GET_LIST_THEATERS";
export const GET_LIST_USERS = "GET_LIST_USERS";