export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_CAROUSELMOVIE = "GET_LIST_CAROUSELMOVIE";
export const GET_LINK_MOVIE = "GET_LINK_MOVIE";