export const GET_LIST_MOVIE = "GET_LIST_MOVIE";
export const GET_DETAIL_MOVIE = "GET_DETAIL_MOVIE";
export const GET_LIST_CAROUSELMOVIE = "GET_LIST_CAROUSELMOVIE";
export const GET_LINK_MOVIE = "GET_LINK_MOVIE";
export const GET_LIST_BRANCHES = "GET_LIST_BRANCHES";
export const GET_LIST_THEATERS = "GET_LIST_THEATERS";
export const GET_LIST_USERS = "GET_LIST_USERS";